### ISSUE TITLE
Feature request: Add map and mapError method for LazyResult

### ISSUE THREAD

**Issue by svdHero** [nvie/lemons.js#439]
Hi there,

the `Result` type has a `map` and a `mapError` method. Could you please add those two methods to the `LazyResult`, too?

I am writing a React frontend and my data model consists of `LazyResult<string, Foo>`. My views make use of `LasyResult.dispatch` for rendering the data.

However, once I have a `Success` instance of `LazyResult<string, Foo>`, I cannot modfiy the data anymore which can be pretty annoying, if the user modifies the data without the need of a server roundtrip.
Also, sometimes I'd like to transform a `Success` instance of `LazyResult<string, Foo>` to a `Success` instance of `LazyResult<string, Bar>`.

Is there any other way to achieve that without the need of a `map` function?

**Comment by svdHero** [comment]
Ah, stupid me. Let me answer my own noob question: One could use `dispatch` itself to do the transformation, right?

I was merely confused, because `dispatch` handles all four cases. So maybe `mapSuccess` and `mapFailure` could still convenient for the sake of less boilerplate typing?

**Comment by nvie** [comment]
Yeah, adding `mapSuccess` and `mapFailure` sound useful!

**Comment by nvie** [comment]
How does #446 look for this?

**Comment by svdHero** [comment]
Looks great! Thanks!

**Comment by nvie** [comment]
This is now available in [v1.6.0](https://github.com/nvie/lemons.js/releases/tag/v1.6.0) 👍
