### ISSUE TITLE
Feature request: Turn Result into LazyResult

### ISSUE THREAD

**Issue by svdHero** [nvie/lemons.js#447]
In my code I have the following function:
```typescript
function ofResult<E,T>(res: Result<E,T>): LazyResult<E,T> {
    if(res.isOk()){
        const value = res.value()
        if(value===undefined)
            throw Error("Unexpected Ok value")
        return Success(value)
    } else {
        const errValue = res.errValue()
        if(errValue===undefined)
            throw Error("Unexpected Err value")
        return Failure(errValue)
    }
}
```
Could this be useful to add to the library out of the box in order to lift results to the lazy world?
I find it quite useful and many F# libraries provide something similar.

**Comment by nvie** [comment]
I love it.

**Comment by svdHero** [comment]
Hm, I've just discovered a weakness in my code. How would you deal with E and/or T being of type `void`? I especially need the case `Result<string, void>` quite often when dealing with commands in a CQRS setting.
This would produce the `"Unexpected Ok value"` exception. I guess I have to remove that check or do you see an alternative there?

**Comment by svdHero** [comment]
Ok, it's even worse, if I remove the
```typescript
if(value===undefined)
    throw Error("Unexpected Ok value")
```
part, I get a typescript compiler error. I'm stuck here. :cry: 
Any ideas how to support both the `void` case and the non-`void` case?

**Comment by nvie** [comment]
You’d have to narrow the type based on the internal `_r`. In Flow, it’s not possible to define custom type assertions on class instances. In TS, it may be possible, but I haven’t experimented with it with class instances yet.

For now, you can narrow the type based on the internal `_r` field:

```js
function ofResult<E,T>(res: Result<E,T>): LazyResult<E,T> {
    return (res._r.type === Ok)
      ? Success(res._r.value)
      : Failure(res._r.error);
}
```

**Comment by svdHero** [comment]
I haven't had time to look into this, but it is still relevant for me.
